In [77]:
import pandas as pd
import numpy as np

#### Q1. Pandas version

What's the version of Pandas that you installed?



In [2]:
pd.__version__

'2.1.4'

#### Getting the data

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

In [34]:
df = pd.read_csv("laptops.csv")

In [6]:
df.head(3)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   
2  ExpertBook  Intel Core i3    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0  
2        789.0

### Q2. Records count

How many records are in the dataset?


In [62]:
df.shape
#2160 rows/records

(2160, 12)

### Q3. Laptop brands
How many laptop brands are presented in the dataset?



In [10]:
df.Brand.nunique()

27

In [11]:
df.Brand.unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

### Q4. Missing values
How many columns in the dataset have missing values?


In [71]:
df.isna().sum().sort_values(ascending=False)
#3 columns have missing values

GPU             1371
Storage type      42
Screen             4
Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Touch              0
Final Price        0
dtype: int64

### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [23]:
df[df['Brand']=="Dell"]['Final Price'].max()

3936.0

### Q6. Median value of Screen
1. Find the median value of Screen column in the dataset. <br>
2. Next, calculate the most frequent value of the same Screen column. <br>
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step. <br>
4. Now, calculate the median value of Screen once again.

In [72]:
#Finding median of screen column
df.Screen.median()

15.6

In [73]:
#Finding most frequent value (aka mode) of screen column
most_frequent = df.Screen.mode()

In [74]:
#filling in missing values of screen column with the mode value from cell 73
df['Screen'] = df['Screen'].fillna(most_frequent)

In [76]:
#recalculating median value
df.Screen.median()
#value has not changed

15.6

### Q7. Sum of weights
1. 
Select all the "Innjoo" laptops from the dataset <br>.2. 
Select only columns RAM, Storage, Scree<br>n3. .
Get the underlying NumPy array. Let's call it<br> 4. X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result <br>X5. TX.
Compute the inverse of<br> 6. XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, <br>17. 100].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the re<br>s8. ult w.
What's the sum of all the elements of the<br> result?

In [38]:
df_Innjoo = df[df['Brand']=="Innjoo"]

In [39]:
df_Innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [41]:
columns = ['RAM', 'Storage', 'Screen']

In [43]:
X = df_Innjoo[columns].values

In [44]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [78]:
X_transpose = X.transpose()
X_transpose

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [79]:
xTx = np.dot(X_transpose, X)
xTx

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [56]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [58]:
xTx_inverse = np.linalg.inv(xTx)

In [80]:
temp = np.dot(xTx_inverse, X_transpose) #calculating product of xTx inv, and x.T
w = np.dot(temp, y)

In [81]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [82]:
w.sum()

91.29988062995815